on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  with-defaults:
    name: Workflow with default configuration
    runs-on: ubuntu-latest
    steps:
      - id: registry
        uses: Sgitario/setup-container-registry@v1
      - name: Pull Hello World for testing
        run: docker pull hello-world:latest
      - name: Test Using Env Var
        run: |
          docker tag hello-world:latest $CONTAINER_REGISTRY_URL/env/image:version
          docker push $CONTAINER_REGISTRY_URL/env/image:version
          docker run $CONTAINER_REGISTRY_URL/env/image:version
      - name: Test Using Output
        run: |
          docker tag hello-world:latest ${{ steps.registry.outputs.container-registry-url }}/output/image:version
          docker push ${{ steps.registry.outputs.container-registry-url }}/output/image:version
          docker run ${{ steps.registry.outputs.container-registry-url }}/output/image:version
  with-config:
    name: Workflow with custom configuration
    runs-on: ubuntu-latest
    steps:
      - id: registry
        uses: Sgitario/setup-container-registry@v1
        with: 
          host: my-registry.com
          port: 3000
      - name: Pull Hello World for testing
        run: docker pull hello-world:latest
      - name: Test Using Env Var
        run: |
          docker tag hello-world:latest $CONTAINER_REGISTRY_URL/env/image:version
          docker push $CONTAINER_REGISTRY_URL/env/image:version
          docker run $CONTAINER_REGISTRY_URL/env/image:version
      - name: Test Using Output
        run: |
          docker tag hello-world:latest ${{ steps.registry.outputs.container-registry-url }}/output/image:version
          docker push ${{ steps.registry.outputs.container-registry-url }}/output/image:version
          docker run ${{ steps.registry.outputs.container-registry-url }}/output/image:version